#!/bin/sh /etc/rc.common
# procd init.d service for podkop_updater (Go daemon)

START=99
STOP=10
USE_PROCD=1

PROG=/usr/bin/podkop_updater

start_service() {
    procd_open_instance
    procd_set_param command "$PROG" --daemon
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 0
    procd_set_param stderr 0
    procd_close_instance
}
